/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import javax.swing.JLabel;

/**
 *
 * @author ackdot
 */
public class PanelMeet extends javax.swing.JPanel {

    /**
     * Creates new form PanelMeet
     */
    public PanelMeet() {
        initComponents();
        display_Timer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTimer = new javax.swing.JLabel();
        buttonChat = new javax.swing.JLabel();
        buttonHand = new javax.swing.JLabel();
        display_Timer = new javax.swing.JLabel();
        buttonNotepad = new javax.swing.JLabel();
        buttonPeople = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonTimer.setForeground(new java.awt.Color(204, 204, 204));
        buttonTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/outline_timer_white_24dp.png"))); // NOI18N
        buttonTimer.setText("Timer");
        buttonTimer.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        buttonChat.setForeground(new java.awt.Color(204, 204, 204));
        buttonChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/outline_chat_white_24dp.png"))); // NOI18N
        buttonChat.setText("Chat");

        buttonHand.setBackground(new java.awt.Color(255, 0, 51));
        buttonHand.setForeground(new java.awt.Color(204, 204, 204));
        buttonHand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/outline_front_hand_white_24dp.png"))); // NOI18N
        buttonHand.setText("Hand");
        buttonHand.setIconTextGap(3);
        buttonHand.setMaximumSize(new java.awt.Dimension(24, 24));
        buttonHand.setMinimumSize(new java.awt.Dimension(24, 24));
        buttonHand.setPreferredSize(new java.awt.Dimension(24, 24));

        display_Timer.setForeground(new java.awt.Color(255, 255, 255));
        display_Timer.setText("00:00:00");
        display_Timer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonNotepad.setForeground(new java.awt.Color(204, 204, 204));
        buttonNotepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/outline_sticky_note_2_white_24dp.png"))); // NOI18N
        buttonNotepad.setText("Notes");

        buttonPeople.setForeground(new java.awt.Color(255, 255, 255));
        buttonPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/outline_group_white_24dp.png"))); // NOI18N
        buttonPeople.setText("5 people");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(buttonHand, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNotepad)
                .addGap(18, 18, 18)
                .addComponent(buttonPeople)
                .addGap(18, 18, 18)
                .addComponent(buttonChat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(display_Timer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonTimer)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(display_Timer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(buttonTimer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChat)
                    .addComponent(buttonHand, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNotepad)
                    .addComponent(buttonPeople))
                .addGap(37, 37, 37))
        );

        getAccessibleContext().setAccessibleName("PanelMeeting");
    }// </editor-fold>//GEN-END:initComponents
    
    public JLabel getbuttonChat(){
        return buttonChat;
    }
    public JLabel getbuttonHand(){
        return buttonHand;
    }
    public JLabel getbuttonPeople(){
        return buttonPeople;
    }
    public JLabel getbuttonNotepad(){
        return buttonNotepad;
    }
    public JLabel getbuttonTimer(){
        return buttonTimer;
    }
    public JLabel getdisplay_Timer(){
        return display_Timer;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonChat;
    private javax.swing.JLabel buttonHand;
    private javax.swing.JLabel buttonNotepad;
    private javax.swing.JLabel buttonPeople;
    private javax.swing.JLabel buttonTimer;
    private javax.swing.JLabel display_Timer;
    // End of variables declaration//GEN-END:variables

    public Object getMeetButton() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
