/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author PC MORGANA
 */
public class UserProfile extends javax.swing.JPanel {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        //this.setSize(500, 610);
        initComponents();
    }


    public JButton getButtonChangeImage() {
        return buttonChangeImage;
    }

    public JTextField getBoxDescription() {
        return boxDescription;
    }

    public JTextField getBoxLastName() {
        return boxLastName;
    }

    public JTextField getBoxName() {
        return boxName;
    }

    public JLabel getNorificationLabel() {
        return norificationLabel;
    }

    public JTextField getBoxPassword() {
        return boxPassword;
    }

    public JTextField getBoxUserName() {
        return boxUserName;
    }

    public JButton getButtonSaveAll() {
        return buttonSaveAll;
    }

    public JLabel getImageIconLabel() {
        return imageIconLabel;
    }
    
    public JLabel getNicknameHeadLabel() {
        return nicknameHeadLabel;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nicknameHeadLabel = new javax.swing.JLabel();
        imageIconLabel = new javax.swing.JLabel();
        buttonChangeImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonSaveAll = new javax.swing.JButton();
        boxUserName = new javax.swing.JTextField();
        boxName = new javax.swing.JTextField();
        boxLastName = new javax.swing.JTextField();
        boxPassword = new javax.swing.JTextField();
        boxDescription = new javax.swing.JTextField();
        norificationLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nicknameHeadLabel.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        nicknameHeadLabel.setText("Usuario");
        nicknameHeadLabel.setHorizontalAlignment(SwingConstants.CENTER);
        add(nicknameHeadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 194, -1));

        imageIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/blank-avatar.png"))); // NOI18N
        add(imageIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 175, 175));

        buttonChangeImage.setText("Change Image");
        add(buttonChangeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 120, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("User Name: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 415, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Last Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 458, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 503, -1, -1));

        buttonSaveAll.setText("Save");
        add(buttonSaveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, -1, -1));

        boxUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(boxUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 310, 30));

        boxName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(boxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 415, 310, 30));

        boxLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(boxLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 458, 310, 30));

        boxPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(boxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 503, 310, 30));

        boxDescription.setHorizontalAlignment(SwingConstants.CENTER);
        add(boxDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, 20));

        norificationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(norificationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 350, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxDescription;
    private javax.swing.JTextField boxLastName;
    private javax.swing.JTextField boxName;
    private javax.swing.JTextField boxPassword;
    private javax.swing.JTextField boxUserName;
    private javax.swing.JButton buttonChangeImage;
    private javax.swing.JButton buttonSaveAll;
    private javax.swing.JLabel imageIconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nicknameHeadLabel;
    private javax.swing.JLabel norificationLabel;
    // End of variables declaration//GEN-END:variables
}
